(ns cljque.api)

(defprotocol Observable
  (observe [observable observer]
    "Subscribes observer to events generated by observable.  Returns a
    no-arg function which unsubscribes the observer."))

(defprotocol Observer
  (message [observer m]
    "Called when an observable this observer is subscribed to
    generates a message m.")
  (done [observer]
    "Called when observable this observer is subscribed to is finished
    generating events.")
  (error [observer e]
    "Called when observable this observer is subscribed to throws an
    exception e."))
